jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
                    id: fos_user.user_provider.username_email

    firewalls:
        main:
          pattern: ^/
          form_login:
            provider: fos_userbundle
            csrf_provider: form.csrf_provider
          logout: true
          anonymous: true

    access_control:
#        - { path: ^/admin/event, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/admin, role: ROLE_ADMIN }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/admin/, role: ROLE_ADMIN }
