<?php

namespace DancePark\DancerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DancerEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DancerEventRepository extends EntityRepository
{
}
