<?php

namespace DancePark\DancerBundle\Entity;

use DancePark\CommonBundle\Entity\DanceType;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\ExecutionContext;

/**
 * DancerDanceType
 *
 * @ORM\Table(name="dancer_dance_type")
 * @ORM\Entity(repositoryClass="DancePark\DancerBundle\Entity\DancerDanceTypeRepository")
 */
class DancerDanceType
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var
     *
     * @ORM\ManyToOne(targetEntity="DancePark\DancerBundle\Entity\Dancer", inversedBy="danceType", cascade={"merge", "persist"})
     */
    private $dancer;

    /**
     * @var DanceType
     *
     * @ORM\ManyToOne(targetEntity="DancePark\CommonBundle\Entity\DanceType", inversedBy="id", cascade={"merge", "persist"})
     */
    private $danceType;

    /**
     * @var
     *
     * @ORM\Column(name="is_pro", type="boolean")
     */
    private $isPro;


    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set dancer
     *
     * @param integer $dancer
     * @return DancerDanceType
     */
    public function setDancer($dancer)
    {
        $this->dancer = $dancer;
    
        return $this;
    }

    /**
     * Get dancer
     *
     * @return integer 
     */
    public function getDancer()
    {
        return $this->dancer;
    }

    /**
     * Set danceType
     *
     * @param integer $danceType
     * @return DancerDanceType
     */
    public function setDanceType($danceType)
    {
        $this->danceType = $danceType;
    
        return $this;
    }

    /**
     * Get danceType
     *
     * @return integer 
     */
    public function getDanceType()
    {
        return $this->danceType;
    }
    /**
     * Constructor
     */
    public function __construct()
    {
        $this->dancer = new \Doctrine\Common\Collections\ArrayCollection();
        $this->danceType = new \Doctrine\Common\Collections\ArrayCollection();
    }
    
    /**
     * Set isPro
     *
     * @param boolean $isPro
     * @return DancerDanceType
     */
    public function setIsPro($isPro)
    {
        $this->isPro = $isPro;
    
        return $this;
    }

    /**
     * Get isPro
     *
     * @return boolean 
     */
    public function getIsPro()
    {
        return $this->isPro;
    }

    public function setName($name)
    {
        return $this->danceType->setName($name); // TODO: Change the autogenerated stub
    }

    public function getName()
    {
        return $this->danceType->getName(); // TODO: Change the autogenerated stub
    }

    public function setDanceGroup($danceGroup)
    {
        return $this->danceType->setDanceGroup($danceGroup); // TODO: Change the autogenerated stub
    }

    public function getDanceGroup()
    {
        return $this->danceType->getDanceGroup(); // TODO: Change the autogenerated stub
    }

    public function setKind($kind)
    {
        return $this->danceType->setKind($kind); // TODO: Change the autogenerated stub
    }

    public function getKind()
    {
        return $this->danceType->getKind(); // TODO: Change the autogenerated stub
    }

    public function getKindLabel()
    {
        return $this->danceType->getKindLabel(); // TODO: Change the autogenerated stub
    }

    public function validateKind(ExecutionContext $context)
    {
        $this->danceType->validateKind($context); // TODO: Change the autogenerated stub
    }
    public function __toString() {
        if ($this->danceType) {
            return $this->danceType->getName();
        }
        return '';
    }
}