<?php

namespace DancePark\DancerBundle\Entity;

use DancePark\CommonBundle\Entity\DanceType;
use Doctrine\ORM\EntityRepository;

/**
 * DancerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DancerRepository extends EntityRepository
{
    /**
     * {@inheritDoc}
     */
    public function findByDancerDanceType(DanceType $type) {
        $queryBuilder = $this->getEntityManager()->createQueryBuilder();
        $queryBuilder
            ->select("e")
            ->from("DancerBundle:Dancer", "e")
            ->innerJoin('e.danceType', 'dt')
            ->where("dt.id = :danceType")
            ->setParameter("danceType", $type->getId());
        $events = $queryBuilder->getQuery()->getResult();

        return $events;
    }

    /**
     * {@inheritDoc}
     */
    public function findByDancerEmailLike($pattern)
    {
        $queryBuilder = $this->getEntityManager()->createQueryBuilder();
        $results = $queryBuilder
            ->select('d')
            ->from('DancerBundle:Dancer', 'd')
            ->where('d.email LIKE :pattern')
            ->setParameter('pattern', $pattern . '%')
            ->getQuery()
            ->getResult();

        return $results;
    }
}
