<?php

namespace DancePark\DancerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DancerDanceTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DancerDanceTypeRepository extends EntityRepository
{
    /**
     * @param $entityId integer
     * @param $list array
     * @return mixed
     */
    public function getTypesForEntityExcludeListed($entityId, $list)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $result = $qb
          ->select('d')
          ->from('DancerBundle:DancerDanceType', 'd')
          ->where($qb->expr()->eq('d.dancer', $entityId));
        if (count($list)) {
          $result->andWhere($qb->expr()->notIn('d.danceType', $list));
        }
        $result = $result->getQuery()
          ->getResult();
        return $result;
    }
}
