<?php

namespace DancePark\DancerBundle\Entity;

use DancePark\EventBundle\Entity\Event;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMapping;
use Doctrine\ORM\Query\ResultSetMappingBuilder;

/**
 * DigestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DigestRepository extends EntityRepository
{
    public function findDigestsByEvent(Event $event) {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $result = $qb->select('d')
            ->from('DancerBundle:Digest', 'd')
            ->innerJoin('d.event', 'e', 'WITH')
            ->where('e.id = :event_id')
            ->setParameter('event_id', $event->getId())
            ->getQuery()
            ->getResult();
        return $result;
    }
}
