<?php

namespace DancePark\CommonBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AddressRegionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddressRegionRepository extends EntityRepository
{
}
