<?php

namespace DancePark\CommonBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DanceTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DanceTypeRepository extends EntityRepository
{
    /**
     * Find DanceType by $name LIKE
     */
    public function findByNameLike($name)
    {
        $queryBuilder = $this->getEntityManager()->createQueryBuilder();

        $results = $queryBuilder
            ->select('dt')
            ->from('CommonBundle:DanceType', 'dt')
            ->where('dt.name LIKE :pattern')
            ->setParameter('pattern', $name . '%')
            ->getQuery()
            ->getResult();
        return $results;
    }

}
