<?php

namespace DancePark\CommonBundle\Entity;

use Doctrine\ORM\EntityNotFoundException;
use Doctrine\ORM\EntityRepository;

/**
 * MetroStationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MetroStationRepository extends EntityRepository
{
    public function findByNameLike($name)
    {
        $queryBuilder = $this->getEntityManager()->createQueryBuilder();

        $queryBuilder
            ->select('ms')
            ->from('CommonBundle:MetroStation', 'ms')
            ->where('ms.name LIKE :name')
            ->setParameter('name', $name . '%')
            ->addOrderBy('ms.name', 'ASC');
        try{
            $result = $queryBuilder->getQuery()->getResult();
        } catch (EntityNotFoundException $e) {
            $result = array();
        }

        return $result;
    }
}
