<?php

namespace DancePark\CommonBundle\Entity;

use DancePark\OrganizationBundle\Entity\Organization;
use Doctrine\ORM\EntityRepository;

/**
 * PlaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaceRepository extends EntityRepository
{
    /**
     * Find DanceType by $name LIKE
     */
    public function findByNameLike($name)
    {
        $queryBuilder = $this->getEntityManager()->createQueryBuilder();

        $results = $queryBuilder
            ->select('p')
            ->from('CommonBundle:Place', 'p')
            ->where('p.name LIKE :pattern')
            ->setParameter('pattern', $name . '%')
            ->getQuery()
            ->getResult();
        return $results;
    }

    public function findByOrganization(Organization $organization) {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $places = $qb->select('p')
            ->from('CommonBundle:Place', 'p')
            ->innerJoin('p.organizations', 'o', 'WITH')
            ->where('o.id = :org')
            ->setParameter('org', $organization->getId())
            ->getQuery()
            ->getResult();
        return $places;
    }

    public function findByMetro(MetroStation $metro) {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $places = $qb->select('p')
            ->from('CommonBundle:Place', 'p')
            ->innerJoin('p.metro', 'o', 'WITH')
            ->where('o.id = :metro')
            ->setParameter('metro', $metro->getId())
            ->getQuery()
            ->getResult();
        return $places;
    }
}
