<?php
namespace DancePark\CommonBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SearchKeywordsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SearchKeywordsRepository extends EntityRepository
{
    /**
     * Find keyword by name operator LIKE
     *
     * @param $name string
     * @param $excluded array
     */
    public function findByNameLikeBut($name, $excluded = array())
    {
        $queryBuilder = $this->getEntityManager()->createQueryBuilder();

        $queryBuilder
            ->select('sk')
            ->from('CommonBundle:SearchKeywords', 'sk')
            ->where('sk.name LIKE :pattern')
            ->setParameter('pattern', $name . '%');

        if (!empty($excluded)) {
            foreach ($excluded as $id => $val) {
                $queryBuilder
                    ->andWhere('sk.name != :val_' . $id)
                    ->setParameter('val_' . $id, $val);
            }

        }

        $results = $queryBuilder->getQuery()
            ->getResult();
        return $results;
    }
}