<?php

namespace DancePark\EventBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EventTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventTypeRepository extends EntityRepository
{
    /**
     * Get event type name by $name operator LIKE
     */
    public function findByNameLike($name)
    {
        $queryBuilder = $this->getEntityManager()->createQueryBuilder();

        $results = $queryBuilder
            ->select('et')
            ->from('EventBundle:EventType', 'et')
            ->where('et.name LIKE :pattern')
            ->setParameter('pattern', $name . '%')
            ->getQuery()
            ->getResult();
        return $results;
    }
}
