<?php

namespace DancePark\EventBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EventTypeGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventTypeGroupRepository extends EntityRepository
{
}
