<?php

namespace DancePark\EventBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EventLessonPriceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventLessonPriceRepository extends EntityRepository
{
}
